In [1]:
#numpy examples and tips and excersices 
#importing numpy 
#two methods of importing
#first method to import numpy as import numpy then enter variable 
# as for example array_1 = numpy.array
import numpy
array_1=numpy.array([13,17,89,45,90,18,300])
print(array_1)
#second method to import also but clarify while import that numpy as np 
#but use shortcut as no.array instead of using numpy
import numpy as np
array_2= np.array([2,65,78,98,76,89])
print(array_2)
#two arrays were printed by two methods 
#take care in variable explorer it is said that these data are array of integar
#convert list into array
list_1=[30,50,70,90]
import numpy as np
print(list_1)
array_3=np.array([30,50,70,90])
#can we try another method to convert dierctly list into array instead of copying data into new variable
print(array_3)
#2d arrays excercise
import numpy as np
array_2d_1=np.array([[3,6,8,9],[13,78,90,70]])
print(array_2d_1)
#3d array excercise take care array data should be the same amount of numbers in bracket.
import numpy as np
array_3d=np.array([[[3,8,9,10],[4,9,10,14]], 
[[50,80,90,99],[70,75,99,102]]])
print(array_3d)

[ 13  17  89  45  90  18 300]
[ 2 65 78 98 76 89]
[30, 50, 70, 90]
[30 50 70 90]
[[ 3  6  8  9]
 [13 78 90 70]]
[[[  3   8   9  10]
  [  4   9  10  14]]

 [[ 50  80  90  99]
  [ 70  75  99 102]]]


In [2]:
#more excersices of numpy
#check dimension of numpy 
#dimension is used to know it is 1d, 2d and 3d
import numpy as np
a=np.array([43])
b=np.array([4,5,6,9])
c=np.array([[3,9,11],[65,78,90]])
d=np.array([[[4,3,6],[8,3,1]],[[56,32,45],[78,34,21]]])
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)
#first one is considered to be scalar
#second one is considered to be 1d array
#third one consider as 2d array 
# fourth one is considered as 3d array 


1
1
2
3


In [2]:
#exercise for numpy for acessing elements
import numpy as np
porosity=np.array([0.15,0.21,0.22,0.35,0.17,0.19])
print(porosity.ndim)
print(porosity)
print(porosity[2], porosity[3])
#excercise for numpy to access element in 2d
pad=np.array([[0.05,0.08,0.09],   #0 in 2d it will take first row while 1 means second row in case of accessing element
              [0.09,0.7,0.04]])
print(pad.ndim)
print(pad)
print(pad[0,2])
print(pad[1,-1])
#array slicing
#2d array slicing
print(pad[1,1:])  
#here he will print first two which means second row in pads and from first variable which means 0.7 to 0.04
#1d array slicing
print(porosity[2:])
#array slice using from to. for 1d
print(porosity[-4:-1])
#array slice using step. for 1d
print(porosity[0:5:2])
#if i donot specify you start from where or end where 
print(porosity[::1])
#array function using random values:
volume_of_shale=np.random.random(size =(2, 4)) # check about size ?? when i use size 2,4 it gives me float numbers why??
print(volume_of_shale)

1
[0.15 0.21 0.22 0.35 0.17 0.19]
0.22 0.35
2
[[0.05 0.08 0.09]
 [0.09 0.7  0.04]]
0.09
0.04
[0.7  0.04]
[0.22 0.35 0.17 0.19]
[0.22 0.35 0.17]
[0.15 0.22 0.17]
[0.15 0.21 0.22 0.35 0.17 0.19]
[[0.71660806 0.86997409 0.41618028 0.92691604]
 [0.75955627 0.40765186 0.83858365 0.01856445]]


In [12]:
#excersice for copy shape and reshape for numpy
#copy example where data is original data while x is copied data
#where i changed in original data while copy remained the same
import numpy as np
data=np.array([4,3,7,98,789,56])
x=data.copy()
data[3]=90 #here i changed value of 98 by using 90
print(data)
print(x)
#if you want also to modify in your copy variable 
#you will use function called view
y=data.view()
print(y)
#The reshape() function returns a new array and can therefore create new objects.
#However if you want to modify the object by modifying the shape, you have to assign a
#tuple containing the new dimensions directly to its shape attribute.
#training for reshape function of numpy
import numpy as np
log_data=np.array([3,6,9,12,15,18,21,24,27,30])
print(log_data.shape)
t=log_data.reshape(2,5)  #when i used (2,5) 2 means 2 rows #starting f reshape function use rows then columns
#while 5 means 5 columns 
print(t)
print(t.shape) #here when you print t.shape it gives how 
#how many columns and rows while ndim give you 1d or 2d or 3d
log_data_1=np.array([3,6,9,12,15,18,21,24,27,30,33,36,47,89,23,56,37,90,28,19,14,67,76,15])
p=log_data_1.reshape(4,3,2) #here means 2 dimension with 3 rows in 2 dimension
print(p)
#when you use rehsape but 3 the third one indicate 
#changing from 1 into 2d
#in previous example you created 2 matrixes

[  4   3   7  90 789  56]
[  4   3   7  98 789  56]
[  4   3   7  90 789  56]
(10,)
[[ 3  6  9 12 15]
 [18 21 24 27 30]]
(2, 5)
[[[ 3  6]
  [ 9 12]
  [15 18]]

 [[21 24]
  [27 30]
  [33 36]]

 [[47 89]
  [23 56]
  [37 90]]

 [[28 19]
  [14 67]
  [76 15]]]


In [5]:
#flattening excersice 
import numpy as np
permeability=np.array([[0.1,10,40,300],[30,50,500,1000]])
NEW_perm=permeability.reshape(-1)
print(permeability)
print(NEW_perm)
#check does array data must be integars or floats it cannot be both of them
#change data into 1,3,2
data=np.array([[1,10,40,300],[2,50,500,1000]])
new_data=data.reshape(-1)
print(new_data)
#using for function with array data
data=np.array([[1,10,40,300],[2,50,500,1000]])
new_data=data.reshape(-1)
print(new_data)
for x in new_data:
    print(x)
#add flatten code for numpy 

[[1.e-01 1.e+01 4.e+01 3.e+02]
 [3.e+01 5.e+01 5.e+02 1.e+03]]
[1.e-01 1.e+01 4.e+01 3.e+02 3.e+01 5.e+01 5.e+02 1.e+03]
[   1   10   40  300    2   50  500 1000]
[   1   10   40  300    2   50  500 1000]
1
10
40
300
2
50
500
1000


In [13]:
#iterating for numpy array
import numpy as np
values=np.array([[1,3,6],[5,8,10]])
print(values)
for x in values:
    print(x)   #in this example he printed first array then second not each 
    #value because x here is consider to be related to arrays not values
    #but if you want to print each element or each value use another nest loops 
    #like y in x
for s in values:
    for y in s:
        print(y)
#so we used nested loops to print all elements in 2d array.


[[ 1  3  6]
 [ 5  8 10]]
[1 3 6]
[ 5  8 10]
1
3
6
5
8
10


In [9]:
#joining of 1d arrays
import numpy as np
data_1=np.array([4,9,15])
data_2=np.array([8,16,36])
combined_data=np.concatenate((data_1,data_2))  #take care two brackets not one
print(combined_data)
#joining of 2d arrays
array_1=np.array([[4,5,10],[90,70,50]])
array_2=np.array([[7,14,18],[87,56,14]])
combined_array=np.concatenate((array_1,array_2), axis=1)
print(combined_array)  #when you say axis =1 it means
# that you will combine them as two rows where first array in both will be combined
#in one row while other will be combined in next row
array_1=np.array([[4,5,10],[90,70,50]])
array_2=np.array([[7,14,18],[87,56,14]])
combined_array=np.concatenate((array_1,array_2), axis=0)
print(combined_array)

[ 4  9 15  8 16 36]
[[ 4  5 10  7 14 18]
 [90 70 50 87 56 14]]
[[ 4  5 10]
 [90 70 50]
 [ 7 14 18]
 [87 56 14]]


In [10]:
#splitting of numpy data 
import numpy as np
logs=np.array([4,3,2,7,9,11,100,8,300])
split_logs=np.array_split(logs,3)
print(split_logs)
#access the splitted array
print(split_logs[0])
print(split_logs[1])
print(split_logs[2])
#split 2d array into three 2d arrays
logs_2d=([[40,70,100,90,70,80],[33,43,64,78,56,45]])
split_logs_2d=np.array_split(logs_2d,3)
print(split_logs_2d)
#check why it gave this results??
#[array([[ 40,  70, 100,  90,  70,  80]]), 
#array([[33, 43, 64, 78, 56, 45]]), 
#array([], shape=(0, 6), dtype=int32)]

[array([4, 3, 2]), array([ 7,  9, 11]), array([100,   8, 300])]
[4 3 2]
[ 7  9 11]
[100   8 300]
[array([[ 40,  70, 100,  90,  70,  80]]), array([[33, 43, 64, 78, 56, 45]]), array([], shape=(0, 6), dtype=int32)]


In [19]:
#array search 
import numpy as np
logs=np.array([1,3,7,9,100])
f=np.where(logs==9)  #9when you search in array you search for value
print(f)
#find indexex where number is even
values=np.array([2,6,8,10,24,53,64,73,101])
k=np.where(values%2 ==0)
print(k)
#find the indexex where values should be inserted when you print 
#place where 64 inserted so you will print 6 because 6
#is index of 64
x=np.searchsorted(values, 64)
print(x)
#soring of array 
nmr=np.array([33,23,21,3])
print(np.sort(nmr))  #sorting is always from smallest to largest
nmr[::-1].sort  #this is function to sort from largest to smallest
print(nmr)


(array([3], dtype=int64),)
(array([0, 1, 2, 3, 4, 6], dtype=int64),)
6
[ 3 21 23 33]
[33 23 21  3]


In [23]:
#sorting 2d array 
import numpy as np
data_array=np.array([[13,6,9,11,24],[74,24,98,14,65]])
print(np.sort(data_array))
#here he do sorting for each array alone without interfer with other arrays
#sorting boolen array
import numpy as np
booelan_data=np.array([True,False,True,False])
print(np.sort(booelan_data))
#check why it make from false to true???


[[ 6  9 11 13 24]
 [14 24 65 74 98]]
[False False  True  True]


In [27]:
#random functions for numpy 
#generate random integars from 0 to 100
import numpy as np
from numpy import random #take care you import two things first numpy
#second you import random
l=random.randint(100)
print(l)  #this means you print everytime
#random values sometimes 24 or 74 or 0 any integar values.
#create random float number from 0 to 1
v=random.rand()
print(v)  #here you print random float value from 0 to
#if i want to create vector value i add new function to 
#first one
q=random.randint(100,size=(5))
print(q) #here he printed random array 5 values
#generate 2d array with 3 rows and each row contain 5 random 
#integars from 0 to 100
r=random.randint(100,size=(3,5))
print(r)


1
0.08274017004854162
[63 79 28 46 66]
[[59 70 74 71  8]
 [69 74  4 90 33]
 [55 83  7 90 28]]


In [1]:
#generate 1d array contain 5 random values:
import numpy as np
from numpy import random
h=random.rand(5)
print(h)  #this example of 1d array for 5 float
#numbers but why when we print it was 0.5 but no 
#float 1.5 or 2.2
from numpy import random  #generate 2d array
#with 3 rows each row contain 5 random numbers
d=random.rand(3,5)
print(d)
u=random.choice([3,7,80,90])
print(u)
p=random.choice([77,99,65,13], size=(3,5))
print(p)  #here he printed random data as 3 rows
# and 5 columns 

[0.10830659 0.54110714 0.22337729 0.56612848 0.43041245]
[[0.32353235 0.18510966 0.22192914 0.32602691 0.58338939]
 [0.91587717 0.58071812 0.50170413 0.46731936 0.28750424]
 [0.13320234 0.25771465 0.17932367 0.09287525 0.90160817]]
90
[[77 77 77 13 13]
 [65 99 99 65 77]
 [77 65 99 65 99]]


In [28]:
#numpy filtering to return value for example higher than 70`
import numpy as np
shearslowness=np.array([80,70,30,180,90])
filter_shearslowness=shearslowness>70
#check this equation, check numpy filtering =!
print(shearslowness[filter_shearslowness])
my_list_osama=[33,65,36,99]
my_array_osama=np.array([33,65,36,99])
print(my_array_osama)

[ 80 180  90]
[33 65 36 99]


In [3]:
#array function using random values:
volume_of_shale=np.random.random(size =(2, 4)) # check about size ?? when i use size 2,4 it gives me float numbers why??
print(volume_of_shale)

[[0.79957    0.76615141 0.70436708 0.94629786]
 [0.8702564  0.90540635 0.62933642 0.32618101]]


In [4]:
#how many columns and rows while ndim give you 1d or 2d or 3d
log_data_1=np.array([3,6,9,12,15,18,21,24,27,30,33,36])
p=log_data_1.reshape(2,3,2)
print(p)
#when you use rehsape but 3 the third one indicate 
#changing from 1 into 2d
#in previous example you created 2 matrixes here 2 means 2 columns and 3 means 3 rows in this example you have
#10 values which means that if you use 2,3,2 it will lead to 2d dimension have two columns with 3 rows


[[[ 3  6]
  [ 9 12]
  [15 18]]

 [[21 24]
  [27 30]
  [33 36]]]


In [8]:
array_2d_1=np.array([[3,6,8,9],[13,78,90,70]])
print(array_2d_1)
copied_2d_array=array_2d_1.copy()
print(copied_2d_array)
#The inverse operation is also possible, that is, you can convert a#two-dimensional #array into a one-dimensional array
# by using the ravel() function.
copied_1d=copied_2d_array.ravel()
print(copied_1d)

[[ 3  6  8  9]
 [13 78 90 70]]
[[ 3  6  8  9]
 [13 78 90 70]]
[ 3  6  8  9 13 78 90 70]


In [10]:
#Another important operation is transposing a matrix, which is inverting the columns
#with the rows. NumPy provides this feature with the transpose() function.
print(array_2d_1)
array_2d_1.transpose()

[[ 3  6  8  9]
 [13 78 90 70]]


array([[ 3, 13],
       [ 6, 78],
       [ 8, 90],
       [ 9, 70]])

In [18]:
logs_2d=([[40,70,100,90,70,80],[33,43,64,78,56,45]])
split_logs_2d=np.array_split(logs_2d,3)
print(split_logs_2d)
#check why it gave this results??
#[array([[ 40,  70, 100,  90,  70,  80]]), 
#array([[33, 43, 64, 78, 56, 45]]), 
#array([], shape=(0, 6), dtype=int32)]

[array([[ 40,  70, 100,  90,  70,  80]]), array([[33, 43, 64, 78, 56, 45]]), array([], shape=(0, 6), dtype=int32)]


In [14]:
#splitting data numpy
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [20]:
#array search 
import numpy as np
logs=np.array([1,3,7,9,100])
f=np.where(logs==9)  #9when you search in array you search for value
print(f)
#find indexex where number is even
values=np.array([2,6,8,10,24,53,64,73,101])
k=np.where(values%2 ==0)
print(k)

(array([3], dtype=int64),)
(array([0, 1, 2, 3, 4, 6], dtype=int64),)


In [25]:
#generate 2d array with 3 rows and each row contain 5 random 
#integars from 0 to 100
import numpy as np
r=random.randint(100,size=(3,5))
print(r)

NameError: name 'random' is not defined

In [8]:
import numpy as np
log_data=np.array([3,6,9,12,15,18,21,24,27,30])
print(log_data.shape)

(10,)


In [21]:
array_1=np.array([[5.2,3,4.5],[90,70,50],[30,13,40]])
array_2=np.array([[9.1,0.1,0.3],[87,56,14],[44,33,14]])
combined_array=np.concatenate((array_1,array_2), axis=0)
print(combined_array)
array_1=np.array([[4,5,10],[90,70,50]])
array_2=np.array([[7,14,18],[87,56,14]])
combined_array=np.concatenate((array_1,array_2), axis=0)
print(combined_array)  #when you say axis =1 it means

[[ 5.2  3.   4.5]
 [90.  70.  50. ]
 [30.  13.  40. ]
 [ 9.1  0.1  0.3]
 [87.  56.  14. ]
 [44.  33.  14. ]]
[[ 4  5 10]
 [90 70 50]
 [ 7 14 18]
 [87 56 14]]
